Always set ENABLE_EXTENDED_COMPRESS_FORMAT
So that declaration of compress_set_next_track_param()
will be found.
"""
vendor/qcom/opensource/audio-hal/primary-hal/hal/audio_hw.c:4018:17: error: implicit declaration of function 'compress_set_next_track_param' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
"""
Change-Id: I96abce52141ac4a677cb4c36f6651fe00f2a7bb5
(cherry picked from commit b6ed772ccaecb439348e4830230a4bbb93abea97)